/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PosterRouteImport } from './routes/poster'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as CompanionsRouteImport } from './routes/companions'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RealmRealmIdRouteImport } from './routes/realm.$realmId'
import { Route as RealmRealmIdPlayRouteImport } from './routes/realm.$realmId_.play'
import { Route as RealmRealmIdPathRouteImport } from './routes/realm.$realmId_.path'
import { Route as RealmRealmIdLevelSlugRouteImport } from './routes/realm.$realmId_.level.$slug'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterRoute = PosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionsRoute = CompanionsRouteImport.update({
  id: '/companions',
  path: '/companions',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmRealmIdRoute = RealmRealmIdRouteImport.update({
  id: '/realm/$realmId',
  path: '/realm/$realmId',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmRealmIdPlayRoute = RealmRealmIdPlayRouteImport.update({
  id: '/realm/$realmId_/play',
  path: '/realm/$realmId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmRealmIdPathRoute = RealmRealmIdPathRouteImport.update({
  id: '/realm/$realmId_/path',
  path: '/realm/$realmId/path',
  getParentRoute: () => rootRouteImport,
} as any)
const RealmRealmIdLevelSlugRoute = RealmRealmIdLevelSlugRouteImport.update({
  id: '/realm/$realmId_/level/$slug',
  path: '/realm/$realmId/level/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codex': typeof CodexRoute
  '/companions': typeof CompanionsRoute
  '/curriculum': typeof CurriculumRoute
  '/parent': typeof ParentRoute
  '/poster': typeof PosterRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/realm/$realmId': typeof RealmRealmIdRoute
  '/realm/$realmId/path': typeof RealmRealmIdPathRoute
  '/realm/$realmId/play': typeof RealmRealmIdPlayRoute
  '/realm/$realmId/level/$slug': typeof RealmRealmIdLevelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codex': typeof CodexRoute
  '/companions': typeof CompanionsRoute
  '/curriculum': typeof CurriculumRoute
  '/parent': typeof ParentRoute
  '/poster': typeof PosterRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/realm/$realmId': typeof RealmRealmIdRoute
  '/realm/$realmId/path': typeof RealmRealmIdPathRoute
  '/realm/$realmId/play': typeof RealmRealmIdPlayRoute
  '/realm/$realmId/level/$slug': typeof RealmRealmIdLevelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codex': typeof CodexRoute
  '/companions': typeof CompanionsRoute
  '/curriculum': typeof CurriculumRoute
  '/parent': typeof ParentRoute
  '/poster': typeof PosterRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRoute
  '/realm/$realmId': typeof RealmRealmIdRoute
  '/realm/$realmId_/path': typeof RealmRealmIdPathRoute
  '/realm/$realmId_/play': typeof RealmRealmIdPlayRoute
  '/realm/$realmId_/level/$slug': typeof RealmRealmIdLevelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codex'
    | '/companions'
    | '/curriculum'
    | '/parent'
    | '/poster'
    | '/settings'
    | '/student'
    | '/realm/$realmId'
    | '/realm/$realmId/path'
    | '/realm/$realmId/play'
    | '/realm/$realmId/level/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codex'
    | '/companions'
    | '/curriculum'
    | '/parent'
    | '/poster'
    | '/settings'
    | '/student'
    | '/realm/$realmId'
    | '/realm/$realmId/path'
    | '/realm/$realmId/play'
    | '/realm/$realmId/level/$slug'
  id:
    | '__root__'
    | '/'
    | '/codex'
    | '/companions'
    | '/curriculum'
    | '/parent'
    | '/poster'
    | '/settings'
    | '/student'
    | '/realm/$realmId'
    | '/realm/$realmId_/path'
    | '/realm/$realmId_/play'
    | '/realm/$realmId_/level/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodexRoute: typeof CodexRoute
  CompanionsRoute: typeof CompanionsRoute
  CurriculumRoute: typeof CurriculumRoute
  ParentRoute: typeof ParentRoute
  PosterRoute: typeof PosterRoute
  SettingsRoute: typeof SettingsRoute
  StudentRoute: typeof StudentRoute
  RealmRealmIdRoute: typeof RealmRealmIdRoute
  RealmRealmIdPathRoute: typeof RealmRealmIdPathRoute
  RealmRealmIdPlayRoute: typeof RealmRealmIdPlayRoute
  RealmRealmIdLevelSlugRoute: typeof RealmRealmIdLevelSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster': {
      id: '/poster'
      path: '/poster'
      fullPath: '/poster'
      preLoaderRoute: typeof PosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companions': {
      id: '/companions'
      path: '/companions'
      fullPath: '/companions'
      preLoaderRoute: typeof CompanionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realm/$realmId': {
      id: '/realm/$realmId'
      path: '/realm/$realmId'
      fullPath: '/realm/$realmId'
      preLoaderRoute: typeof RealmRealmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realm/$realmId_/play': {
      id: '/realm/$realmId_/play'
      path: '/realm/$realmId/play'
      fullPath: '/realm/$realmId/play'
      preLoaderRoute: typeof RealmRealmIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realm/$realmId_/path': {
      id: '/realm/$realmId_/path'
      path: '/realm/$realmId/path'
      fullPath: '/realm/$realmId/path'
      preLoaderRoute: typeof RealmRealmIdPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realm/$realmId_/level/$slug': {
      id: '/realm/$realmId_/level/$slug'
      path: '/realm/$realmId/level/$slug'
      fullPath: '/realm/$realmId/level/$slug'
      preLoaderRoute: typeof RealmRealmIdLevelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodexRoute: CodexRoute,
  CompanionsRoute: CompanionsRoute,
  CurriculumRoute: CurriculumRoute,
  ParentRoute: ParentRoute,
  PosterRoute: PosterRoute,
  SettingsRoute: SettingsRoute,
  StudentRoute: StudentRoute,
  RealmRealmIdRoute: RealmRealmIdRoute,
  RealmRealmIdPathRoute: RealmRealmIdPathRoute,
  RealmRealmIdPlayRoute: RealmRealmIdPlayRoute,
  RealmRealmIdLevelSlugRoute: RealmRealmIdLevelSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
